name: FirstJoinPlus
main: com.chaseoes.firstjoinplus.FirstJoinPlus
version: 2.5.0
description: FirstJoinPlus 1.13+ by Kazra.
author: chaseoes
dev-url: http://dev.bukkit.org/server-mods/firstjoinplus/
website: http://dev.bukkit.org/server-mods/firstjoinplus/
softdepend: [GeoIPTools]
commands:
  firstjoinplus:
    description: FirstJoinPlus command(s).
    aliases: fjp
    usage: /firstjoinplus [reload|setspawn|debug]
permissions:
  firstjoinplus.reload:
    description: Permission to use the /firstjoinplus reload command.
  firstjoinplus.setspawn:
    description: Permission to use the /firstjoinplus setspawn command.
  firstjoinplus.debug:
    description: Permission to use the /firstjoinplus debug command.